name: rhodyds
channels:
  - conda-forge
dependencies:
  - ipykernel
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - plotnine
  - plotly
  - seaborn
  - scikit-learn
  - mystmd
  - jupytext
  - huggingface_hub
  - skops
  - imagio
  - ipywidgets
  # - jupyterlab_myst